apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager
  namespace: task-manager
  labels:
    app: task-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-manager
  template:
    metadata:
      labels:
        app: task-manager
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: task-manager
          image: ghcr.io/osccarjr/pipelinecd-procesos:latest
          imagePullPolicy: Always
          args:
            - python
            - main.py
          env:
            - name: LD_SDK_KEY
              valueFrom:
                secretKeyRef:
                  name: launchdarkly-secret
                  key: sdk-key
            - name: LD_FLAG_KEY
              value: enable-advanced-statistics
