apiVersion: v1
kind: Service
metadata:
  name: task-manager
  labels:
    app: task-manager
spec:
  selector:
    app: task-manager
  ports:
    - port: 80
      targetPort: 8000  # o el puerto donde expongas tu API
      protocol: TCP
  type: ClusterIP
